x-cucumber-build: &cucumber-build
  context: ./
  dockerfile: Dockerfile
x-cucumber-depends-on: &cucumber-depends-on
  - selenium-hub
  - firefoxnode
  - chromenode

version: "3.7"
services:
  selenium-hub:
      image: selenium/hub 
      container_name: selenium-hub 
      ports:
      - 4444:4444
      networks:
      - cucumberNetwork

  firefoxnode:
      image: selenium/node-firefox-debug
      volumes:
        - /dev/shm:/dev/shm
      depends_on:
      - selenium-hub
      ports:
        # VNC: See what's going on by connecting your VNC client to 0.0.0.0:5901
        - 5901:25900
      environment:
        - HUB_HOST=selenium-hub
        - HUB_PORT=4444
      networks:
      - cucumberNetwork
    
  chromenode:
      image: selenium/node-chrome-debug
      volumes:
        - /dev/shm:/dev/shm
      depends_on: 
      - selenium-hub
      ports:
        # VNC: See what's going on by connecting your VNC client to 0.0.0.0:5901
        - 5900:25900
      environment:
        - HUB_HOST=selenium-hub
        - HUB_PORT=4444
      networks:
      - cucumberNetwork

  cucumber:
    build: *cucumber-build  
    command: ["bash", "-c", "sleep 10 && cucumber -p wip_web_ff_remote"]
    depends_on: *cucumber-depends-on
    ports:
      - 8010:8010
    networks:
      - cucumberNetwork
    volumes:
      - /dev/shm:/dev/shm
      - /Users/mhondar/docker/cucumber/report:/usr/src/app/cucumber-rap/features/reports/report_builder
      - /Users/mhondar/docker/cucumber/logs:/usr/src/app/cucumber-rap/features/logs

networks: 
  cucumberNetwork: